#define _USE_MATH_DEFINES
#include <cmath>
#include "Spline.h"

//
// offx, offy, offz represent the shift in indices from center position
// sigma_spline -> standard deviation of a Gaussian that approximates the B-spline
//
Spline::Spline(const int order, const bool is2D)
    : neighbours(order + 1), order(order), is2D(is2D), offx{}, offy{}, offz{} {
    if (order == 3) {
        init_order_3();
    } else if (order == 2) {
        init_order_2();
    } else if (order == 1) {
        init_order_1();
    }
}

void Spline::init_order_3() {
    this->offset = 0.0;
    this->sigma_spline = std::sqrt(9.0 / (8.0 * M_PI));
    offx = {-1, 0, 1, 2};
    offy = {-1, 0, 1, 2};
    offz = {-1, 0, 1, 2};
}

void Spline::init_order_2() {
    this->offset = 0.5;
    this->sigma_spline = std::sqrt(8.0 / (9.0 * M_PI));
    offx = {-1, 0, 1};
    offy = {-1, 0, 1};
    offz = {-1, 0, 1};
}

void Spline::init_order_1() {
    this->offset = 0.0;
    this->sigma_spline = 0.4;  // TODO: proper value for order 1
    offx = {0, 1};
    offy = {0, 1};
    offz = {0, 1};
}

std::array<double, 4> Spline::spline(const double d) const {

    if (order == 3) {
        // In the model, we use a standard cubic B-spline centered around the voxel's position to assign a prior
        // probability that the voxel was generated by one of four nodes: the two nodes on the immediate left
        // and right of where the voxel falls, plus the two nodes to the left and right of those, respectively.
        // All other nodes will have prior probability zero of having generated the voxel.
        //
        // The definition of a standard cubic B-spline (centered around value zero) is given by (cf. UnserSPM1999
        // eq. 6):
        //
        //   B( x ) = ( 2/3 - abs(x)^2 + abs(x)^3/2 ) if abs(x) < 1
        //            ( 2 - abs(x) )^3 / 6            if 1 <= abs( x ) < 2
        //            0                               otherwise.
        //
        // In the implementation below, I evaluate B( x ) at the four locations ( x =-d-1; x=-d; x=1-d; x=2-d )
        // where d is the distance betw
        // een the voxel's assumed position and the node position immediately left
        // of that (so that 0<=d<1).
        const double d2 = d * d;                // Precompute d^2
        const double d3 = d2 * d;              // Precompute d^3
        const double one_minus_d = 1.0 - d;    // Precompute (1 - d)
        const double one_minus_d2 = one_minus_d * one_minus_d; // Precompute (1 - d)^2
        const double one_minus_d3 = one_minus_d2 * one_minus_d; // Precompute (1 - d)^3
        return {
        one_minus_d3 / 6.0,
        2.0 / 3.0 - d2 + d3 * 0.5,
        2.0 / 3.0 - one_minus_d2 + one_minus_d3 * 0.5,
        d3 / 6.0
        };
    }
    if (order == 2) {
        // The definition of a standard quadratic B-spline (centered around value zero) is given by
        //
        //   B( x ) = 3/4 - abs(x)^2         if abs(x) < 0.5
        //            1/8 (2 abs(x) - 3)^2   if 0.5 <= abs(x) < 1.5
        //            0                      otherwise.
        // In the implementation below, I evaluate B( x ) at the three locations ( x=-d-1; x=-d; x=1-d )
        // where d is the distance between the voxel's assumed position and the closest node position immediately
        const double d2 = d * d;               // Precompute d^2
        const double d2_neg = -2.0 * d;        // Precompute -2d
        const double d2_neg_1 = d2_neg + 1.0; // Precompute -2d + 1
        const double d2_neg_2 = d2_neg - 1.0; // Precompute -2d - 1
        return {
        0.125 * (d2_neg_1 * d2_neg_1), // ( -2d + 1 )^2
        0.75 - d2,                      // 0.75 - d^2
        0.125 * (d2_neg_2 * d2_neg_2), // ( -2d - 1 )^2
        0.0
        };
    }
    {
        // The definition of a standard linear B-spline (centered around value zero) is given by
        //
        //   B( x ) = 1 - abs(x)     if 0 <= abs(x) < 1
        //            0              otherwise.
        // In the implementation below, I evaluate B( x ) at the two locations ( x=-d; x=1-d )
        // where d is the distance between the voxel's assumed position and the node position immediately left
        // of that (so that 0<=d<1).
        return {
        1 - d,
        d,
        0.0,
        0.0,
        };
    }
}

std::array<double, 4> Spline::log_spline(const double d) const {

    std::array<double, 4> o;

    if (order == 3) {
        if (d < 1e-300) {
            o[3] = -1e100;
        } else {
            o[3] = 3 * std::log(d) - std::log(6.0);
        }
        o[0] = 3 * std::log(1.0 - d) - std::log(6.0);
        o[1] = std::log(2.0 / 3.0 - d * d + std::pow(d, 3) / 2.0);
        o[2] = std::log(2.0 / 3.0 - std::pow((1.0 - d), 2) + std::pow((1.0 - d), 3) / 2.0);

    } else if (order == 2) {
        if (d > 0.5) {
            o = {-1e100, -1e100, -1e100};
        } else {
            o[0] = std::log(0.125 * std::pow(-2.0 * d + 1.0, 2));
            o[1] = std::log(0.75 - d * d);
            o[2] = std::log(0.125 * std::pow(-2.0 * d - 1.0, 2));
        }
    } else {
        if (d >= 1) {
            o[0] = -1e100;
        } else {
            o[0] = std::log(1 - d);
        }
        if (d < 1e-300) {
            o[1] = -1e100;
        } else {
            o[1] = std::log(d);
        }
    }
    return o;
}